export const routePath = {
  login: "/login",
  signup: "/signup",
  studentwallet: "/student-wallet",
  studentwalletredemption: "/student-wallet-redemption",
  studentrewards: "/student-rewards",
  main: "/main",
  home: "/",
  studentdashboard: "/student-dashboard",
  scholarshipdiscovery: "/scholarship-discovery",
  scholarshipmatch: "/scholarship-match",
  sponsordashboard: "/sponsor-dashboard",
  studentredemptioncalog: "/student-redemption-catalog",
  sponsordashboardreport: "/sponsor-dashboard/report",
  studentrewardsredemption: "/student-rewards-redemption",
  studentprofile: "/student-profile",
  ViewStudentProfile:"/view-profile",
  sponsorprofile:"/sponsor-profile",
  ViewSponsorProfile:"/view-sponsor-profile",
  studentmessages:"/student-messages",
};
